world: rtp
minX: -1000
maxX: 1000
minZ: -1000
maxZ: 1000
teleportMessage: '&x&F&F&B&0&0&0▍ &x&F&F&B&0&0&0&lR&x&F&F&9&6&0&0&lT&x&F&F&7&C&0&0&lP &fВы были телепортированы в &6случайное место'
cooldown: 10 # время в секундах между использованиями команды /rtp для каждого игрока
